### ISSUE TITLE
LKG_Packages are out-of-date

### ISSUE THREAD

**Issue by ericstj** [dotnet/versions#161]
I noticed that for CoreCLR and CoreFx that LKG_Packages are out of date.  I'd expect these to have the last shipped stable packages, but instead it looks like they have the first shipped stable packages (EG: RTM, not servicing).

**Comment by dagood** [comment]
Updating LKG_Packages is a manual step that never made it into the release checklists, so it didn't happen. Created https://github.com/dotnet/buildtools/issues/1514 to track automation. Do you mind making a PR for the manual update this time?
