### ISSUE TITLE
Release 2.1's Host etc link is broken

### ISSUE THREAD

**Issue by wli3** [dotnet/versions#214]
![image](https://user-images.githubusercontent.com/6993335/35463805-6236518c-02a7-11e8-8a8b-19879917e97d.png)

https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1

**Comment by dagood** [comment]
This was fixed, thanks. Didn't see we had an issue for it--this repo's issues aren't particularly monitored.
