### ISSUE TITLE
Add link to aspnetcore-runtime

### ISSUE THREAD

**Issue by wli3** [dotnet/versions#215]
To successful install dotnet-sdk.deb or rpm, aspnetcore-runtime, Runtime Host, Host FX Resolver ,Shared Framework are required.

Other than aspnetcore-runtime, rest of them are in the list.

**Comment by dagood** [comment]
This was added.

But a recent change in the aspnet asset structure caused the readme section to stop appearing. That issue's now tracked by https://github.com/dotnet/core-eng/issues/2612 which is in PR now.
