### ISSUE TITLE
Disable Maestro for release/uwp6.0

### ISSUE THREAD

**Issue by joshfree** [dotnet/versions#217]
tracking issue for https://github.com/dotnet/corefx/pull/26316#issuecomment-361321976

**Comment by zamont** [comment]
Fixed by #219 . @joshfree I'm unable to close the issue.

**Comment by zamont** [comment]
I may not have collaborator status and my PR wasn't commented correctly to close this.

**Comment by joshfree** [comment]
I'll close it.  Let's follow up offline on permissions.
