### ISSUE TITLE
Add link to aspnetcore-runtime

### ISSUE THREAD

**Issue by wli3** [dotnet/versions#238]
https://github.com/dotnet/versions/issues/215

Sorry that I cannot reopen it. But it is missing in the latest 2.1 and 2.1-preview1

**Comment by dagood** [comment]
This is tracked by https://github.com/dotnet/core-eng/issues/2612, which is in the validation phase.  (Waiting for the next build to hit this execution path.) I've updated the title to make it clearer it includes this fix.
