### ISSUE TITLE
Update download links to point to upgradeable native linux installers

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/versions#295]
After the work has been completed in https://github.com/dotnet/core-setup/issues/4097, we should update the links in this repo to point to the upgradeable ones.

For example at https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1:
https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-1/20180510-02/final/assets/aspnetcore/Runtime/2.1.0-rtm-30765/aspnetcore-runtime-2.1.0-rtm-30765-x64.deb
needs to be changed to 
https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-1/20180510-02/final/assets/aspnetcore/Runtime/2.1.0-rtm-30765/aspnetcore-runtime-2.1.0-rtm-30765-x64-upgrade.deb

This will need updates to the core-setup installers as well as the aspnetcore installers and will require changes in the release/2.1 page. The changes have also been made in master/dev but is there a page tracking those builds?

cc @wli3 @livarcocc @natemcmaster @Petermarcu

**Comment by dagood** [comment]
Issue moved to [dotnet/core-eng #3478](https://github.com/dotnet/core-eng/issues/3478) via [**ZenHub**](https://www.zenhub.com/)

**Comment by dagood** [comment]
This repo contains readme.md, but it is generated by infrastructure elsewhere. Please file issues in https://github.com/dotnet/core-eng for readme.md contents.
