### ISSUE TITLE
Azure 2.1.1 Runtime 

### ISSUE THREAD

**Issue by eopeter** [dotnet/versions#318]
When will the .NET Core 2.1 .1 Runtime be available in Azure?

**Comment by dagood** [comment]
This repo isn't for general .NET Core questions. @leecow can you help point @eopeter at the right place to get this info?

**Comment by leecow** [comment]
@eopeter , we're finishing up some publishing activities today. I would expect it to be available in limited regions in the next day and worldwide by Monday.
