### ISSUE TITLE
CoreCLR subscription job is failing

### ISSUE THREAD

**Issue by tannergooding** [dotnet/versions#429]
It looks like the CoreCLR subscription job has been failing since https://github.com/dotnet/coreclr/pull/22525 was merged with:
```
Searching for Visual Studio 2017 or later installation
Visual Studio 2017 or later not found
Error: Visual Studio 2017 or 2019 required.
       Please see https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md for build instructions.
```

It looks like this is likely due to us dropping support for VS2015.

**Comment by tannergooding** [comment]
CC. @dagood, @jkotas

**Comment by dagood** [comment]
Moving to CoreCLR, nobody tracks dotnet/versions issues.

**Comment by dagood** [comment]
Issue moved to [dotnet/coreclr #22646](https://github.com/dotnet/coreclr/issues/22646) via [**ZenHub**](https://www.zenhub.com/)
