### ISSUE TITLE
No version information found for System.Threading.Tasks.Extensions 4.5.2

### ISSUE THREAD

**Issue by rhegner** [dotnet/versions#502]
I'm using this repository to automatically locate the sources for a set of assemblies (we need to do this in our company for compliance reasons).

However I can't find "System.Threading.Tasks.Extensions 4.5.2" in this repository.

My tool did work fine for "System.Threading.Tasks.Extensions 4.5.1", which can be found in 
\build-info\dotnet\corefx\release\2.2\Latest_Packages.txt

So could you please add information for "System.Threading.Tasks.Extensions 4.5.2" to this repository, so that my tool can automatically locate its sources?

Alternatively, could you please tell me which version of the corefx repo does contain version 4.5.2 of that assembly?

**Comment by dagood** [comment]
It looks like this has been answered over at https://github.com/dotnet/corefx/issues/40827, you can find this info in the package itself. The dotnet/versions repo isn't the best way to do this.

In theory, the package is listed here, though:

https://github.com/dotnet/versions/blob/2bc42016e4066a5a95352c8452114f78cc08e516/build-info/dotnet/product/cli/release/2.1.7/build.xml#L164
