### ISSUE TITLE
Allow @dotnet/dnceng to approve/merge PRs

### ISSUE THREAD

**Issue by premun** [dotnet/versions#665]
As every repo will be changing their subscription during the Master-to-Main renaming, we will have a high volume of pull requests to this repo that will need to be approved/merged. Currently, a very limited amount of people have those permissions.

I suggest it would be good to allow the whole @dotnet/dnceng to have these permissions as First Reponders will be the main point of contact for repo owners who go through the renaming.

/cc @mmitche

**Comment by emmyforeignet** [comment]
Allow @dotnet/dnceng to approve/merge PRs #665

**Comment by premun** [comment]
This has already been set up, closing
