### ISSUE TITLE
Move Maestro to its own repository

### ISSUE THREAD

**Issue by dagood** [dotnet/versions#83]
There's no pressing need to do this, but some soft reasons Maestro doesn't fit here:
- Maestro listens to other repos too, not just build-info changes.
- Changes under the `Maestro` path (typically subscription updates) are independent of build-info changes.
- All changes to build-infos are automated, with the small exception of manual fixups. All changes to Maestro are manual subscription changes.
- Many teams will want to write to and read from build-infos for build coordination, but Maestro is a service.

No concrete plan to make the move--for now, it's waiting for a hard reason.

/cc @naamunds @dleeapho

**Comment by markwilkie** [comment]
I recommend we make any improvements in this area in concert with the work to build from source.

/cc @ellismg

**Comment by deeprobin** [comment]
Maestro still uses .NET Framework.

If there is interest (and Maestro has not yet been replaced by anything else) I can create a small Maestro rewrite.

But I would like to ask a maintainer if we still need Maestro in the long run.

**Comment by dagood** [comment]
> If there is interest (and Maestro has not yet been replaced by anything else) I can create a small Maestro rewrite.

Maestro is still being used fairly heavily, but I'm not sure if there's interest in updating it (let alone a rewrite). However, I would recommend asking at https://github.com/dotnet/arcade/issues for a definitive answer from the team that maintains it now.

**Comment by markwilkie** [comment]
Hi @deeprobin - curious what you'd like to see Maestro do that it currently doesn't and the application?

Cheers

**Comment by deeprobin** [comment]
@mmitche 
Allright. I haven't gone that deep into the matter yet.
I thought there was only one Maestro.

How many use cases do we still have from the legacy Maestro in the Foundation?
It would make sense to migrate to the new Maestro in the long term and to remove the Legacy Maestro from this repository (and move it to an archive repository if necessary).

**Comment by mmitche** [comment]
It's mainly used for code mirroring and inter-branch merge PR generation these days.

Code mirroring will probably move into new Maestro (it's inefficient as it is), and the inter-branch merge generation could probably be moved to fabric bot or something like that. Haven't looked into it too closely.
