### ISSUE TITLE
Maestro should use a build account user agent for queueing builds 

### ISSUE THREAD

**Issue by naamunds** [dotnet/versions#97]
Currently, Maestro queues builds with @eerhardt as the user agent (e.g. https://devdiv.visualstudio.com/DevDiv/_build/explorer?_a=summary&buildId=396022).  A build account user agent should be used instead.

**Comment by naamunds** [comment]
This entails deciding which account to use, and then updating the `VsoPassword` app setting in Azure with an access token for it.

**Comment by dagood** [comment]
`dn-bot` is being used now.
